version: '3'

services:
  ai-service:
    container_name: ai-service
    build:
      context: .
      dockerfile: ./ai-service/Dockerfile
    environment:
      - MINIO_ENDPOINT=dev-minio.leamech.com
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECURE=true
      - MINIO_SECRET_KEY=mIn!0#2023_S3cureKey
      - REDIS_HOST=dev-valkey.leamech.com
      - REDIS_PASSWORD=v@lk3y#2023_C@che!
      - REDIS_PORT=6379
    volumes:
      - ./ai-service:/app
      - ./utils:/app/utils
    networks:
      - app-network

  frame-service:
    container_name: frame-service
    build:
      context: .
      dockerfile: ./frame-service/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - REDIS_HOST=dev-valkey.leamech.com
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=dev-minio.leamech.com
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECURE=true
      - MINIO_SECRET_KEY=mIn!0#2023_S3cureKey
      - REDIS_PASSWORD=v@lk3y#2023_C@che!
    volumes:
      - ./frame-service:/app
      - ./utils:/app/utils
    networks:
      - app-network
  
  mapping-service:
    container_name: mapping-service
    build:
      context: .
      dockerfile: ./mapping-service/Dockerfile
    environment:
      - REDIS_HOST=dev-valkey.leamech.com
      - REDIS_PORT=6379
      - REDIS_PASSWORD=v@lk3y#2023_C@che!
    volumes:
      - ./mapping-service:/app
      - ./utils:/app/utils
    ports:
      - "5005:5005"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data: 