version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5003:5003"  # Host:Container
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=negar-dev
      - MINIO_SECRET_KEY=negar-dev
      - REDIS_HOST=34.55.93.180
      - REDIS_PORT=6379
    volumes:
      - ./:/app  # Mount current directory to /app in container
      - /app/__pycache__  # Prevent __pycache__ from being created on host
      - /app/.pytest_cache  # Prevent test cache from being created on host
    depends_on:
      - minio
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: "negar-dev"
      MINIO_ROOT_PASSWORD: "negar-dev"
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio_data:/data
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

  ai-service:
    build: 
      context: ./ai-service
      dockerfile: Dockerfile
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=negar-dev
      - MINIO_SECRET_KEY=negar-dev
      - REDIS_HOST=34.55.93.180
      - REDIS_PORT=6379
    depends_on:
      - minio
      - flask-app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  minio_data: 