version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5003:5003"  # Host:Container
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - REDIS_HOST=34.55.93.180
      - REDIS_PORT=6379
    volumes:
      - ./:/app  # Mount current directory to /app in container
      - /app/__pycache__  # Prevent __pycache__ from being created on host
      - /app/.pytest_cache  # Prevent test cache from being created on host
    depends_on:
      - minio
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  minio_data: 